from typing import Any, Optional

class AnyMarkupError(Exception):
    cause: Any = ...
    original_tb: Any = ...
    def __init__(self, cause: Any, original_tb: str = ...) -> None: ...

def parse(inp: Any, format: Optional[Any] = ..., encoding: str = ..., force_types: bool = ..., interpolate: bool = ...): ...
def parse_file(path: Any, format: Optional[Any] = ..., encoding: str = ..., force_types: bool = ..., interpolate: bool = ...): ...
def serialize(struct: Any, format: Any, target: Optional[Any] = ..., encoding: str = ...): ...
def serialize_file(struct: Any, path: Any, format: Optional[Any] = ..., encoding: str = ...): ...
