from typing import Any

class HookCallError(Exception): ...

class _Result:
    def __init__(self, result: Any, excinfo: Any) -> None: ...
    @property
    def excinfo(self): ...
    @property
    def result(self): ...
    @classmethod
    def from_call(cls, func: Any): ...
    def force_result(self, result: Any) -> None: ...
    def get_result(self): ...

class _LegacyMultiCall:
    hook_impls: Any = ...
    caller_kwargs: Any = ...
    firstresult: Any = ...
    def __init__(self, hook_impls: Any, kwargs: Any, firstresult: bool = ...) -> None: ...
    results: Any = ...
    def execute(self): ...
