from typing import Any, Optional

class Picker:
    options: Any = ...
    title: Any = ...
    indicator: Any = ...
    multiselect: Any = ...
    min_selection_count: Any = ...
    options_map_func: Any = ...
    all_selected: Any = ...
    index: Any = ...
    custom_handlers: Any = ...
    def __init__(self, options: Any, title: Optional[Any] = ..., indicator: str = ..., default_index: int = ..., multiselect: bool = ..., multi_select: bool = ..., min_selection_count: int = ..., options_map_func: Optional[Any] = ...) -> None: ...
    def register_custom_handler(self, key: Any, func: Any) -> None: ...
    def move_up(self) -> None: ...
    def move_down(self) -> None: ...
    def mark_index(self) -> None: ...
    def get_selected(self): ...
    def get_title_lines(self): ...
    def get_option_lines(self): ...
    def get_lines(self): ...
    scroll_top: Any = ...
    def draw(self) -> None: ...
    def run_loop(self): ...
    def config_curses(self) -> None: ...
    def start(self): ...

def pick(*args: Any, **kwargs: Any): ...
