#+TITLE: Contributing

* Prerequisites
** Poetry
You will need ~poetry~ installed in your machine.
Poetry helps you declare, manage and install dependencies of Python projects, ensuring you have the right stack everywhere.

[[https://github.com/python-poetry/poetry][Poetry Github repository]]

Installing using

#+BEGIN_SRC sh
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
#+END_SRC

More instructions on their Github repository.

* Develop

Before you git push a new module make sure unit tests are also
included. Test are to be written using ~pytest~.

For more information look into [[https://www.freecodecamp.org/news/test-driven-development-what-it-is-and-what-it-is-not-41fa6bca02a2/][Test Driven Development]].

** For developers install normal and dev dependencies

#+BEGIN_SRC sh
poetry install
#+END_SRC

** Install dev dependencies

#+BEGIN_SRC sh
poetry add -D pytest
#+END_SRC
** Install normal dependencies

#+BEGIN_SRC sh
poetry add numpy
#+END_SRC

** Use poetry shell

#+BEGIN_SRC sh
poetry shell
#+END_SRC

* Testing

Install [[https://tox.readthedocs.io/en/latest/index.html][tox]] on your machine globally or in a separate venv, then run:

#+BEGIN_SRC sh
tox
#+END_SRC

** Testing using Gitlab runner locally

*** Prerequisites

- Docker
  You need docker installed, because we will be using the =docker= executor for the gitlab-runner.

*** Install =gitlab-runner= locally

**** MacOS

***** Install using brew

#+BEGIN_SRC
brew install gitlab-runner
#+END_SRC

***** Register it with gitlab

#+BEGIN_SRC
gitlab-runner register
#+END_SRC

***** Options

| Option                  | Value                               |
|-------------------------+-------------------------------------|
| =gitlab-ci coordinator= | https://gitlab.com                  |
| =gitlab-ci description= | Enter some description              |
| =gitlab-ci tags=        | Enter some tags                     |
| =Executer=              | =docker=                            |
| =default docker image=  | Enter the name of some docker image |

*** Running the tests

#+begin_src
gitlab-runner exec docker test
#+end_src

* Coverage report

Coverage report is automatically generated for the master branch by [[https://coveralls.io/gitlab/justinekizhak/devinstaller][coveralls.io]]

* Facing any problems

** Issue with installing poetry packages

Try setting LANG variable for the shell, if its not set.

*** Copy paste this line into your =~/.bash_profile= or =~/.zshrc=.

#+BEGIN_SRC sh
export $LANG = en_US.UTF-8
#+END_SRC

After this you might need to reopen the terminal.

*** Reinstall Python using brew

The default python installation from Xcode is not built using SSL support. So
you may have problem installing packages.

Reinstall python using this command on the terminal:

#+BEGIN_SRC sh
brew reinstall python
#+END_SRC

* Git

This project uses the [[https://www.conventionalcommits.org/en/v1.0.0/][Conventional git commit specs]].

* Changelog

Changelog is generated using =git-chglog=. See [[https://github.com/git-chglog/git-chglog][git-chglog]].

** Usage

#+BEGIN_SRC sh
git-chglog -o CHANGELOG.md
#+END_SRC

* Versioning

This project uses [[https://semver.org/][Semver versioning]].

Version management is done using =poetry=.

** Commands

For more command check [[https://python-poetry.org/docs/cli/#version][poetry versioning]].

*** To bump up major version

#+BEGIN_SRC sh
poetry version major
#+END_SRC

*** To bump up minor version

#+BEGIN_SRC sh
poetry version minor
#+END_SRC

*** To bump up patch version

#+BEGIN_SRC sh
poetry version patch
#+END_SRC

* Type checking

You can type check this project. Type hints are provided.

To check you need =tox=. You can install =tox= globally or in a virtualenv.

#+BEGIN_SRC sh
tox -e type
#+END_SRC

** Stub generation

Type checking for external packages need stubs.

To generate stub pop into poetry shell and run:

#+BEGIN_SRC sh
stubgen -p PACKAGE_NAME
#+END_SRC

* Dependencies

** Application specific

These dependencies are inside the =pyproject.toml=.

*** Dependencies required to develop docs locally

These are also in =pyproject.toml=, but in the =dev-dependencies= section.

** ReadTheDocs specific

Dependencies required for ReadTheDocs are in =docs/reqirements.txt=.

* Local Variables :noexport:
# Local variables:
# eval: (add-hook 'after-save-hook 'org-pandoc-export-to-rst t t)
# end:
