from typing import Any

CSI: str
OSC: str
BEL: str

def code_to_chars(code: Any): ...
def set_title(title: Any): ...
def clear_screen(mode: int = ...): ...
def clear_line(mode: int = ...): ...

class AnsiCodes:
    def __init__(self) -> None: ...

class AnsiCursor:
    def UP(self, n: int = ...): ...
    def DOWN(self, n: int = ...): ...
    def FORWARD(self, n: int = ...): ...
    def BACK(self, n: int = ...): ...
    def POS(self, x: int = ..., y: int = ...): ...

class AnsiFore(AnsiCodes):
    BLACK: int = ...
    RED: int = ...
    GREEN: int = ...
    YELLOW: int = ...
    BLUE: int = ...
    MAGENTA: int = ...
    CYAN: int = ...
    WHITE: int = ...
    RESET: int = ...
    LIGHTBLACK_EX: int = ...
    LIGHTRED_EX: int = ...
    LIGHTGREEN_EX: int = ...
    LIGHTYELLOW_EX: int = ...
    LIGHTBLUE_EX: int = ...
    LIGHTMAGENTA_EX: int = ...
    LIGHTCYAN_EX: int = ...
    LIGHTWHITE_EX: int = ...

class AnsiBack(AnsiCodes):
    BLACK: int = ...
    RED: int = ...
    GREEN: int = ...
    YELLOW: int = ...
    BLUE: int = ...
    MAGENTA: int = ...
    CYAN: int = ...
    WHITE: int = ...
    RESET: int = ...
    LIGHTBLACK_EX: int = ...
    LIGHTRED_EX: int = ...
    LIGHTGREEN_EX: int = ...
    LIGHTYELLOW_EX: int = ...
    LIGHTBLUE_EX: int = ...
    LIGHTMAGENTA_EX: int = ...
    LIGHTCYAN_EX: int = ...
    LIGHTWHITE_EX: int = ...

class AnsiStyle(AnsiCodes):
    BRIGHT: int = ...
    DIM: int = ...
    NORMAL: int = ...
    RESET_ALL: int = ...

Fore: Any
Back: Any
Style: Any
Cursor: Any
