from .ansitowin32 import AnsiToWin32 as AnsiToWin32
from typing import Any, Optional

orig_stdout: Any
orig_stderr: Any
wrapped_stdout: Any
wrapped_stderr: Any
atexit_done: bool

def reset_all() -> None: ...
def init(autoreset: bool = ..., convert: Optional[Any] = ..., strip: Optional[Any] = ..., wrap: bool = ...) -> None: ...
def deinit() -> None: ...
def colorama_text(*args: Any, **kwargs: Any) -> None: ...
def reinit() -> None: ...
def wrap_stream(stream: Any, convert: Any, strip: Any, autoreset: Any, wrap: Any): ...
